"""Build script: build React app and embed index.html into Python for Vercel deployment."""
import subprocess
import sys
from pathlib import Path

def main():
    root = Path(__file__).parent
    frontend = root / "frontend"
    public = root / "public"
    
    # 1. Build React app
    print("Building React app...")
    result = subprocess.run(
        "npm ci && npm run build",
        cwd=frontend,
        shell=True,
    )
    if result.returncode != 0:
        sys.exit(1)
    
    # 2. Copy to public
    build_dir = frontend / "build"
    public.mkdir(exist_ok=True)
    for f in build_dir.iterdir():
        if f.is_file():
            (public / f.name).write_bytes(f.read_bytes())
        else:
            dest = public / f.name
            dest.mkdir(exist_ok=True)
            for sf in f.rglob("*"):
                if sf.is_file():
                    rel = sf.relative_to(f)
                    (dest / rel).parent.mkdir(parents=True, exist_ok=True)
                    (dest / rel).write_bytes(sf.read_bytes())
    
    # 3. Embed index.html into Python module
    index_path = public / "index.html"
    if not index_path.exists():
        print("ERROR: index.html not found after build")
        sys.exit(1)
    
    html = index_path.read_text(encoding="utf-8")
    # Use repr to safely escape for Python
    html_repr = repr(html)
    
    embed_path = root / "embedded_index.py"
    embed_path.write_text(
        f'# Auto-generated by build_embed.py - do not edit\n'
        f'INDEX_HTML = {html_repr}\n',
        encoding="utf-8",
    )
    print(f"Embedded index.html ({len(html)} chars) into {embed_path.name}")

if __name__ == "__main__":
    main()
